### ISSUE TITLE
[Q] Would you still use GLConstants.GLGRAPHICS here?

### ISSUE THREAD

**Issue by blausand** [kosowski/Geometry-shaders-Processing#1]
Nicely done!
I haven't heard of the `GLConstants.GLGRAPHICS` renderer before. Since your example is from 2013:
Would you still use this renderer or is the `P3D` much the same in terms of performance by now?
I'm thinking of using **vertex shaders** within **processing** on a **Raspberry** for some live visual installation, that's why i'm asking.
Sorry for (ab-)using the issue form, can't find comment or discussion forms for github projects.

**Comment by kosowski** [comment]
GLGraphics was an openGL wrapper library for Processing 1. Most of its functionality was introduced in Processing's P2D and P3D renderer since version 2. You can find vertex and fragment shaders code samples in Processing's examples, and geometry shader examples on the forum.
